### PR TITLE
Simplify test projects

### PR DESCRIPTION
**Pull request by 0xced**
## What does this PR do?

This PR extracts all the common properties across all test projects (except for `Testcontainers.Commons`) into the `Directory.Build.props` file.

## Why is it important?

This reduces duplication and makes it easier to maintain test projects.

## Related issues

None

### CODE REVIEW

**Review by HofmeisterAn — COMMENTED** [review]
Thank you for submitting your pull request. In general, it is recommended to discuss pull requests beforehand to minimize unnecessary work ([Contributing](https://dotnet.testcontainers.org/contributing/)). I am aware of the current configuration (copy and paste), and it is intentionally.

We are considering the implementation of a multi-repo approach, which is why I made an effort to ensure that the module dependencies remain as autonomous as possible. THB, I am uncertain how to continue here. For a single-repo approach the changes make sense /cc @kiview.

**Comment by 0xced** [comment]
I read the contributing guide but felt that this pull request did not fall into the _anything big_ category. It may look big by the number of files involved but it was merely a search and replace on multiple files. 😉

About the multi-repo approach, I'm not sure it would be a benefit for this project. With 16 open issues and 8 open pull requests it still seems manageable. But I'm not a maintainer so of course I'll let this decision up to you.

**Comment by HofmeisterAn** [comment]
I spoke with the other TC maintainers, and right now, we do not want to increase coupling across modules, etc. We prefer self-contained configurations.

We really appreciate your help, and it is difficult for me to not accept your PR. Your changes are fine from a technical standpoint, and I understand the intention. But we do not want to make any changes in this direction yet.

**Comment by 0xced** [comment]
The amount of code duplication still itches me but I understand your decision.

**Pull request closed without merging**
