### PR TITLE
feat: Add `WithLogger(ILogger)` builder API

### LINKED ISSUE #996: [Enhancement]: ILogger should be injected into all AbstractBuilder subclasses
### Problem

Shipping a default console logger that works with any .NET test framework has been dismissed as impossible to do by VSTest engineers in https://github.com/microsoft/vstest/issues/4125. Yet we'd still want to collect logs in xUnit.net.

### Solution

Injecting an `ILogger` into all AbstractBuilder subclasses would allow to pass a logger implementation that writes logs to xUnit's [ITestOutputHelper](https://xunit.net/docs/capturing-output). I have started prototyping this in my [ILoggerInjection](https://github.com/0xced/testcontainers-dotnet/tree/ILoggerInjection) branch but it's far from complete.

I'm not familiar enough with other testing frameworks but I hope they have a similar solution to xUnit's ITestOutputHelper. I think that NUnit captures the console output so it might already work with the current ConsoleLogger implementation.

### Benefit

The Testcontainers logs can be captured when running unit tests in xUnit.net.

Here's the output when running `dotnet test --logger "console;verbosity=detailed"` for **Testcontainers.PostgreSql.Tests** (still in my [ILoggerInjection](https://github.com/0xced/testcontainers-dotnet/tree/ILoggerInjection) branch)

```
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 6.0.21)
[xUnit.net 00:00:00.54]   Discovering: Testcontainers.PostgreSql.Tests
[xUnit.net 00:00:00.58]   Discovered:  Testcontainers.PostgreSql.Tests
[xUnit.net 00:00:00.58]   Starting:    Testcontainers.PostgreSql.Tests
  Passed Testcontainers.PostgreSql.PostgreSqlContainerTest.ConnectionStateReturnsOpen [278 ms]
  Standard Output Messages:
 [testcontainers.org 00:00:00.120] Connected to Docker:
   Host: npipe://./pipe/docker_engine
   Server Version: 24.0.5
   Kernel Version: 5.15.90.1-microsoft-standard-WSL2
   API Version: 1.43
   Operating System: Docker Desktop
   Total Memory: 5.79 GB
 [testcontainers.org 00:00:01.843] Docker container 4f8851616709 created
 [testcontainers.org 00:00:01.856] Start Docker container 4f8851616709
 [testcontainers.org 00:00:03.322] Wait for Docker container 4f8851616709 to complete readiness checks
 [testcontainers.org 00:00:04.356] Docker container 4f8851616709 ready
 [testcontainers.org 00:00:04.502] Delete Docker container 4f8851616709


[xUnit.net 00:00:07.53]   Finished:    Testcontainers.PostgreSql.Tests
  Passed Testcontainers.PostgreSql.PostgreSqlContainerTest.ExecScriptReturnsSuccessful [188 ms]
  Standard Output Messages:
 [testcontainers.org 00:00:00.057] Docker container 495bfd1b3892 created
 [testcontainers.org 00:00:00.065] Start Docker container 495bfd1b3892
 [testcontainers.org 00:00:01.451] Wait for Docker container 495bfd1b3892 to complete readiness checks
 [testcontainers.org 00:00:01.462] Docker container 495bfd1b3892 ready
 [testcontainers.org 00:00:01.478] Copy tar archive to "/" to Docker container 495bfd1b3892
 [testcontainers.org 00:00:01.491] Execute "psql --username postgres --dbname postgres --file /tmp/e91386fd-e7c4-44b2-b7d3-dcb8be088409/oso2tyro.p1a" at Docker container 495bfd1b3892
 [testcontainers.org 00:00:01.656] Delete Docker container 495bfd1b3892
```

### Alternatives

No other alternatives were considered to solve this issue.

### Would you like to help contributing this enhancement?

Yes

### PR DESCRIPTION
**Pull request by 0xced**
## What does this PR do?

This pull request moves the logger configuration from the static `TestcontainersSettings` class to the AbstractBuilder class.

Before:
```csharp
TestcontainersSettings.Logger = logger;
```

After:
```csharp
new TBuilderEntity().WithLogger(logger).Build()
```

## Why is it important?

This will enable a seamless integration with xUnit.net (both with `ITestOutputHelper` and with `IMessageSink`).

## Related issues

Fixes #996

### CODE REVIEW

**Comment by 0xced** [comment]
Continuing discussion from https://github.com/testcontainers/testcontainers-dotnet/pull/1093#discussion_r1485208704 to here (where it belongs).

> The PR does not contain the Xunit project, right? I think it is a good idea!

Indeed this pull request does include the new Xunit project. I will submit another pull request dedicated to the new Xunit integration.

> A lot of developers will benefit from it. I have not taken a close look into the PR that involves the changes to the logging implementation yet. I took a quick look, and it is quite big.

It's big because it removes the `ILogger` parameter from all containers in all modules but the actual change in ``AbstractBuilder`4.cs`` is suprisingly small.

> IIRC, I proposed to split it into two steps: one that provides an internal WithLogger(ILogger) builder method, and another that makes the necessary changes regarding logging the container runtime information and making the method public. After that, we can add the dedicated Xunit, package. WDYT? Splitting it makes reviewing much easier.

I tried but I don't see how it's possible to split in two steps. Again, if you ignore the required changes in the modules the core feature diff is not that big.

**Comment by HofmeisterAn** [comment]
I haven't had the time yet, but I will review it in the next few days.

**Comment by 0xced** [comment]
Great, I'll refrain from submitting new pull requests in the meantime. 😉

**Review by HofmeisterAn — COMMENTED** [review]
It took me some time to review everything, and as I got closer to completion, I identified and refactored a couple of crucial parts. As mentioned in a previous comment, I would like to avoid logging the runtime information either too frequently (as is the case now) or just once in cases where developers cannot easily find it. While it still requires some polishing, I believe we are very close now. I have included tests to ensure that the runtime information is only logged once per logger instance (`LoggerTest`). This guarantees the presence of the runtime information in cases where developers use the `ITestOutputHelper`, which, IMO, looks quite good. I can provide more details and necessary follow-ups tomorrow, but for today, I am finished and tired. If you have some time to review the changes as well, that would be awesome and much appreciated. I am certain that we can make further improvements.

**Comment by HofmeisterAn** [comment]
The PR is ready for a final review. @0xced your feedback is much appreciated (no hurry). I am happy to merge the PR afterward.

**Comment by 0xced** [comment]
Awesome, I'll try to have a look this week.

**Comment by 0xced** [comment]
I just pushed 1ee0e3e56358fef9e2e501741107cd86901989f1 which uses the configured `ILogger` for the resource reaper too.

I think the configured logger should also be passed to the `PortForwardingContainer`, I'm looking into it…

**Comment by HofmeisterAn** [comment]
> I think the configured logger should also be passed to the `PortForwardingContainer`, I'm looking into it…

We can also change this with a follow-up PR. Probably, we simply need to replace the singleton property with a method that provides an ILogger overload.

**Comment by 0xced** [comment]
OK, let's take care of `PortForwardingContainer` in a follow up PR.

I see that you removed the structured logging of runtime information that I had introduced. I re-introduced it in a slightly improved way in fef7faaf93c8b9e7ff199071011a22d2556f44ff. I think it makes the `LogContainerRuntimeInfoAsync` implementation much easier to read and also it's the [_right_ way](https://messagetemplates.org) to do structured logging. But if you don't like it, just drop the commit.

One last question: why did you introduce an empty `TestcontainersSettings` static constructor in e535cbec9dacc98a499efdcaaa6883f9db83f8cf?

**Comment by HofmeisterAn** [comment]
> I think it makes the `LogContainerRuntimeInfoAsync` implementation much easier to read and also it's the [_right_ way](https://messagetemplates.org) to do structured logging. But if you don't like it, just drop the commit.

Can we please revert it? I really do not like it, and structured logging does not have a lot of benefits here. I would like to remove `Logging` anyway in the future. Logging the message immediately is much easier. Happy to merge the pull request afterward and publish a beta version.

**Comment by 0xced** [comment]
OK fine, I’ll revert.

What about the empty `TestcontainersSettings` static constructor?

> Happy to merge the pull request afterward and publish a beta version.

Could you please have a look at #1139 before publishing? I promise it’s much simpler than this one. 😉

**Comment by HofmeisterAn** [comment]
> What about the empty `TestcontainersSettings` static constructor?
> 
> >

This guarantees lazy initialization (probably not really important here), see _beforefieldinit_.

> Could you please have a look at #1139 before publishing? I promise it’s much simpler than this one. 😉

Yes, we can merge this before publishing a beta version too.

**Comment by 0xced** [comment]
I just pushed 1bf2f9689197779419974c91fcf3d52bb9772a3c which removes the structure logging and I extracted the logging code into a new method for improved readability, and also catching only the exceptions when running `GetSystemInfoAsync` and `GetVersionAsync`.

> This guarantees lazy initialization (probably not really important here), see beforefieldinit.

Wow, I had no idea, gotta agree with [Mike Marynowski](https://github.com/dotnet/csharplang/issues/3080#issuecomment-571206390)!

> [...] controlling the timing of when you want a class to run its static initialization shouldn't be controlled entirely by the presence or absence of a static constructor, that's just so odd...

I think it's now ready to be merged. 😀

**Review by HofmeisterAn — APPROVED** [review]

**Pull request merged**
