### PR TITLE
[UPDATE]

### PR DESCRIPTION
**Pull request by navidZee**
remove setter from Username property

### CODE REVIEW

**Review by HofmeisterAn — COMMENTED** [review]
Thanks for your PR. Can you add some context to your change? Why is this important? The MSSQL container does not allow to set a username. Removing the setter might be misleading.

**Comment by navidZee** [comment]
I think when we create ability to set a value to properties, should not throw **NotImplementedException**.
I got confused when using testcontainers to create mssql database. Because following code has error,
image
and when i remove Username property from first initialize that was fine. 
image

**Comment by HofmeisterAn** [comment]
> I think when we create ability to set a value to properties, should not throw **NotImplementedException**.

This behavior is intended. You cannot set the username in the MSSQL Docker container image that easy.

The first screenshot would be misleading if it won't throw an exception. 1) The user is not created as expected, 2) the connection string contains a wrong username, and you won't be able to connect to the database. I think there are two ways to improve it. Either add custom code that creates the user (similar to the database) or add more context (message) to the exception.

**Comment by HofmeisterAn** [comment]
I will close this PR. As mentioned above, this behavior is intended. If you would like to add one of the suggestions above, please follow the [main contributing guidelines](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/docs/contributing.md).

**Pull request closed without merging**
