### PR TITLE
feat: Add BigQuery module

### PR DESCRIPTION
**Pull request by dejandjenic**
this PR implements Google BigQuery support

### CODE REVIEW

**Comment by dejandjenic** [comment]
@HofmeisterAn  can you please take a look at this PR

**Comment by HofmeisterAn** [comment]
> @HofmeisterAn can you please take a look at this PR

I will try to review it until the end of this week. I am sorry the past few days were busy. However, you need to look into the [failing test](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/6586107484/job/17893795194?pr=1034#step:9:1874) first.

**Comment by dejandjenic** [comment]
@HofmeisterAn this was a bit tricky one, sorry for the delay, can you please take a look

**Comment by HofmeisterAn** [comment]
> @HofmeisterAn this was a bit tricky one, sorry for the delay, can you please take a look

I will review it within the next few days as soon as I find some free time 👍.

**Comment by HofmeisterAn** [comment]
I will look at it later the day.

**Pull request merged**
