### PR TITLE
[#470] #BUGFIX 'assemblyName: DotNet.Testcontainers; function: Docker…

### PR DESCRIPTION
**Pull request by bohlenc**
…Image'

{Consider hostname of image prefix when configured.}

### CODE REVIEW

**Review by HofmeisterAn — APPROVED** [review]
👏

**Comment by bohlenc** [comment]
Hi @HofmeisterAn,

can you give any ETA on when we can get this merged?

**Comment by HofmeisterAn** [comment]
> Hi @HofmeisterAn,
> 
> can you give any ETA on when we can get this merged?

I can merge it in my lunch break.

**Comment by bohlenc** [comment]
> > Hi @HofmeisterAn,
> > can you give any ETA on when we can get this merged?
> 
> I can merge it in my lunch break.

Great, thank you!

**Comment by HofmeisterAn** [comment]
Published in `1.7.0-beta.2269`, closes #470.

**Pull request closed without merging**
