### PR TITLE
Added WithBuildArgument method to ImageFromDockerfileBuilder

### PR DESCRIPTION
**Pull request by michal-korniak**
Some images requires arguments for build process. This PR enable to use this option with the framework.

### CODE REVIEW

**Review by HofmeisterAn — COMMENTED** [review]
Thanks for your pull request 🙏. Do you think we can cover it via a unit test?

**Comment by michal-korniak** [comment]
I don't know how to test it. Remember that these kind of variables are present only during build time.

**Review by HofmeisterAn — APPROVED** [review]
> I don't know how to test it. Remember that these kind of variables are present only during build time.

Yeah, I couldn't think of anything either.

**Review by HofmeisterAn — COMMENTED** [review]
Can you take a look at the tests?

**Review by HofmeisterAn — APPROVED** [review]
Thanks. I’ll merge it tomorrow.

**Comment by HofmeisterAn** [comment]
Thanks again for your work https://github.com/testcontainers/testcontainers-dotnet/commit/39671c01d057567ae0ad505925236be27550982c.

**Pull request closed without merging**
