### PR TITLE
feat: add azure sql edge test container configuration

### PR DESCRIPTION
**Pull request by riezebosch**
## What does this PR do?

Add support for Azure SQL Edge test containers.

## Why is it important?

Only SQL variant that runs on MacBook M1 🤘🏻

## Related issues

No issues.

## How to test this PR

Running the new integration test will suffice.

## Follow-ups

Including a dedicated test container is optional.

### CODE REVIEW

**Review by HofmeisterAn — COMMENTED** [review]
The module configuration looks good, thanks. Unfortunately, it follows the old approach. I will finalize the new module API next week. Do you mind if we wait until #729 is done? Then we do not have to migrate afterwards again.

**Comment by riezebosch** [comment]
I couldn't easily see what's changed in the API and needed to adapt.  All current modules are in the folder `_OBSOLETE_`, but there's no example of how to do it from now on?

**Comment by HofmeisterAn** [comment]
Modules won't be part of the Testcontainers project anymore. We will move them to their own projects in this repository (mono repository). This allows much more complex modules and features. We will start to migrate current modules after the release of `2.4.0`.

I am working on a follow-up blog post and documentation that explains how to implement a module. There will be two types of modules. Simple modules can just inherit from `ContainerBuilder`. More advanced modules need to inherit from `ContainerBuilder<TBuilderEntity, TContainerEntity, TConfigurationEntity>`. We added a .NET [template](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src/Templates) (CSharp) to scaffold advanced modules quickly from CLI. It contains example code and documentation already.

Migrating Azure SQL Edge will be pretty straight forward. It requires to override and extend the container build default configuration and a custom wait strategy.

**Comment by HofmeisterAn** [comment]
The documentation (article) is not yet ready, but I was able to implement a Microsoft SQL Server module (#757) which is pretty similar to Azure SQL Edge I think. If you would like to take a look at it in the meantime you can scaffold a module by running:

```console
git clone --branch develop git@github.com:testcontainers/testcontainers-dotnet.git
cd ./testcontainers-dotnet/
dotnet new --install ./src/Templates
dotnet new tcm --name PostgreSql --official-module true --output ./src
dotnet sln add ./src/Testcontainers.PostgreSql/Testcontainers.PostgreSql.csproj
```

**Pull request closed without merging**
