### PR TITLE
fix: Bump MSSQL image version, remove Azure SQL Edge and Papercut module

### PR DESCRIPTION
**Pull request by HofmeisterAn**
## What does this PR do?

With the recent VM image update (`Ubuntu-22.04`) for GitHub-hosted runners and Microsoft-hosted agents, we encounter issues where the MSSQL and Azure SQL Edge modules crash during container startup. We experienced similar issues with `Ubuntu-24.04`.

We need to update the MSSQL version to one that is compatible with the new VM image: `mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04`. Usually, we try to avoid updating module image versions to prevent breaking changes, and we recommend that developers pin the image version. If you encounter this issue, please use the container builder API (`WithImage(string)`) to update the image accordingly:

    WithImage("mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04")

Unfortunately, we also need to remove the Azure SQL Edge module and mark the NuGet dependency as deprecated. There is no new version available, and the image is [EOL](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-sql-edge-update-september-2023/ba-p/3930827) anyway.

@TechLiam I decided to remove the Papercut module as well. The pipeline frequently fails when sending or receiving SMTP messages. We can add the module again if it becomes stable and someone takes responsibility for addressing the issues/module.

I am  really sorry for the inconvenience, especially since this is the second issue with the MSSQL module in such a short time. I want to stress that both issues were caused by upstream changes, and we are working to address them and provide fixes/workaround quickly.

🚩 FYI: We saw other images failing too, but these are the two we are using in Testcontainers for .NET.

## Why is it important?

Our CI pipeline keeps failing. We need to address the issue to get it running again.

## Related issues

- Relates https://github.com/actions/runner-images/issues/10646
- Relates https://github.com/actions/runner-images/issues/10649
- Relates https://github.com/testcontainers/testcontainers-dotnet/issues/1264

### CODE REVIEW

**Comment by TechLiam** [comment]
That is fair enough on removing the Papercut module I do use it so would be happy to support and take ownership of it can you point me to the logs for the problem to take a look @HofmeisterAn 
Or is it to do with this if so then ok I understand https://github.com/testcontainers/testcontainers-dotnet/issues/1136

**Comment by HofmeisterAn** [comment]
@TechLiam Initially, it failed with the following [error](https://github.com/testcontainers/testcontainers-dotnet/runs/30374716242#r34):

> System.Net.Mail.SmtpException: The operation has timed out.

I tried several changes to stabilize it, but unfortunately, nothing worked. I switched to `SendAsync`, which no longer threw the `SmtpException`, but then receiving the message timed out.

So basically, what I tried was this:

```diff
diff --git a/tests/Testcontainers.Papercut.Tests/PapercutContainerTest.cs b/tests/Testcontainers.Papercut.Tests/PapercutContainerTest.cs
index 6feba9c..5ed6add 100644
--- a/tests/Testcontainers.Papercut.Tests/PapercutContainerTest.cs
+++ b/tests/Testcontainers.Papercut.Tests/PapercutContainerTest.cs
@@ -23,17 +23,19 @@ public sealed class PapercutContainerTest : IAsyncLifetime

         Message[] messages;

+        using var timeoutCts = new CancellationTokenSource(TimeSpan.FromSeconds(30));
+
         using var httpClient = new HttpClient();
         httpClient.BaseAddress = new Uri(_papercutContainer.GetBaseAddress());

         using var smtpClient = new SmtpClient(_papercutContainer.Hostname, _papercutContainer.SmtpPort);

         // When
-        smtpClient.Send("from@example.com", "to@example.com", subject, "A test message");
+        smtpClient.SendAsync("from@example.com", "to@example.com", subject, "A test message", null);

         do
         {
-            var messagesJson = await httpClient.GetStringAsync("/api/messages")
+            var messagesJson = await httpClient.GetStringAsync("/api/messages", timeoutCts.Token)
                 .ConfigureAwait(true);

             var jsonDocument = JsonDocument.Parse(messagesJson);
```

The pipeline failed after 30 seconds with the following [error](https://github.com/testcontainers/testcontainers-dotnet/runs/30394857308#r34):

> System.Threading.Tasks.TaskCanceledException: The operation was canceled.

Then I reduced the HTTP client timeout to 1 second and retried getting the message, but this didn’t work either (receiving timeout). Right now, I believe there is an issue where Papercut is not receiving or processing the message correctly. Maybe the wait strategy indicates readiness too early, and we send the message too soon—I'm not sure.

**Comment by TechLiam** [comment]
Issued a PR to reintroduce the module https://github.com/testcontainers/testcontainers-dotnet/pull/1268
I've added the wait strategy I think that needed for the test to not be flakey

**Comment by philipnguyxn** [comment]
Encountered this issue again on Azure DevOps pipeline with a self-hosted agent image even when using the suggested `WithImage("mcr.microsoft.com/mssql/server:2022-latest")` / `WithImage("mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04")` workaround. Tested locally on a Mac M1 Pro didn't encounter the error. 

Image info:
```
OS: linux-x64
Dotnet SDK: ^8.0
```

**Comment by kwaazaar** [comment]
This issue is not solved for me. It appears ALWAYS when I run multiple tests in parallel (run all tests from VS) on my dev-laptop. Not om my dev-desktop. On my laptop I have Docker Desktop use WSL2. On my desktop I have not. Maybe that enables to reproduce this.

**Pull request merged**
