### PR TITLE
Added WithTmpfsMount(...) builder.

### PR DESCRIPTION
**Pull request by chrisbbe**
#516 Solved

### CODE REVIEW

**Review by HofmeisterAn — APPROVED** [review]

**Comment by HofmeisterAn** [comment]
LGTM! Thanks.

**Comment by HofmeisterAn** [comment]
https://github.com/testcontainers/testcontainers-dotnet/commit/da34ecb5ea41bb32d84b02270ac3fd56580f3aae, closes #516.

**Comment by kfrajtak** [comment]
Great work! When this will be released?

**Comment by HofmeisterAn** [comment]
No ETA yet. If you need a version I can publish a snapshot release.

**Comment by kfrajtak** [comment]
That would be cool. Thanks.

**Comment by HofmeisterAn** [comment]
`2.2.0-beta.2760496496`

**Pull request closed without merging**
